### ISSUE TITLE
undefined method 'import' when assets:precompile in prod

### ISSUE THREAD

**Issue by rossjones** [biola/turnout#58]
When I run assets:precompile for our prod environment

```
RAILS_ENV=production bin/rake assets:precompile  --trace
```

I get the following error ...

```
4: from bin/rake:3:in `<main>'
3: from bin/rake:3:in `require'
2: from ...ruby-2.6.3@.../gems/turnout-2.5.0/lib/turnout/rake_tasks.rb:3:in `<top (required)>'
1: from from ...ruby-2.6.3@.../gems/turnout-2.5.0/lib/turnout/rake_tasks.rb:3:in `each'
from ...ruby-2.6.3@.../gems/turnout-2.5.0/lib/turnout/rake_tasks.rb:3:in 
`block in <top (required)>': undefined method `import' for main:Object (NoMethodError
```

I'm not sure why `assets:precompile` is doing this in Rails 5.2.3 but presumably I'm doing something wrong.

**Comment by rossjones** [comment]
This appears to have been a false alarm. Another error elsewhere `content_security_policy` seems to have been swallowed and for some reason raised it's head this way.
